# urlpatterns = [
#     path('accounts/', include('allauth.urls')),
# ]

from django.urls import path,include,re_path
from .views import *
urlpatterns = [
     path('accounts/', include('allauth.urls')),
	 path('university/', UniversityViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='university_list'),
	 path('university/<int:pk>/', UniversityViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='university_detail'),
	 path('professor/', ProfessorViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='professor_list'),
	 path('professor/<int:pk>/', ProfessorViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='professor_detail'),
	 path('student/', StudentViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='student_list'),
	 path('student/<int:pk>/', StudentViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='student_detail'),
	 path('userprofile/', UserProfileViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='userprofile_list'),
	 path('userprofile/<int:pk>/', UserProfileViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='userprofile_detail'),
	 path('courses/', CoursesViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='courses_list'),
	 path('courses/<int:pk>/', CoursesViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='courses_detail'),
	 path('kabinet/', KabinetViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='kabinet_list'),
	 path('kabinet/<int:pk>/', KabinetViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='kabinet_detail'),
	 path('raspisanie/', RaspisanieViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='raspisanie_list'),
	 path('raspisanie/<int:pk>/', RaspisanieViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='raspisanie_detail'),
	 path('zapic/', ZapicViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='zapic_list'),
	 path('zapic/<int:pk>/', ZapicViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='zapic_detail'),
	 path('dz/', DZViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='dz_list'),
	 path('dz/<int:pk>/', DZViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='dz_detail'),
	 path('sdacha/', SdachaViewSets.as_view({'get': 'list', 'post': 'create'}),
		name='sdacha_list'),
	 path('sdacha/<int:pk>/', SdachaViewSets.as_view({'get': 'retrieve', 'put': 'update', 'delete': 'destroy'}),
		name='sdacha_detail'),
]