# Generated by Django 5.0.6 on 2024-06-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='title_en',
            field=models.CharField(help_text='Введите название университета', max_length=64, null=True, unique=True, verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='university',
            name='title_ky',
            field=models.CharField(help_text='Введите название университета', max_length=64, null=True, unique=True, verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='university',
            name='title_ru',
            field=models.CharField(help_text='Введите название университета', max_length=64, null=True, unique=True, verbose_name='Университет'),
        ),
    ]
